{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.watchNamespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
{{- if .Values.watchNamespace }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  name: {{ template "druid-operator.fullname" . }}
  labels:
    {{- include "druid-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - '*'
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - '*'
- apiGroups:
    - extensions
  resources:
    - ingresses
  verbs:
    - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - druid-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - druid.apache.org
  resources:
  - '*'
  verbs:
  - '*'
{{- end }}
