{{- if .Values.rbac.create }}
{{- $env := .Values.env }}
{{- $operatorName := (include "druid-operator.fullname" .) -}}
{{- if and ($env.WATCH_NAMESPACE) (ne $env.WATCH_NAMESPACE "default") }}
# Split WATCH_NAMESPACE by commas and loop on them
{{- $watchedNamespaces := (split "," $env.WATCH_NAMESPACE) -}}
{{- range $watchedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ . }}
  name: {{ $operatorName }}
  labels:
    {{- include "druid-operator.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "druid-operator.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $operatorName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "druid-operator.fullname" . -}}-sc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "druid-operator.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "druid-operator.serviceAccountName" $ }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "druid-operator.fullname" . }}-sc
  apiGroup: rbac.authorization.k8s.io

{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $operatorName }}
  labels:
    {{- include "druid-operator.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "druid-operator.serviceAccountName" $ }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $operatorName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}

