{{- if .Values.rbac.create }}
{{- $env := .Values.env }}
{{- if and ($env.WATCH_NAMESPACE) (ne $env.WATCH_NAMESPACE "default") }}
# Split WATCH_NAMESPACE by commas and loop on them
{{- $watchedNamespaces := (split "," $env.WATCH_NAMESPACE) -}}
{{- range $watchedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ . }}
  name: {{ template "druid-operator.fullname" $ }}
  labels:
    {{- include "druid-operator.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - watch
      - create
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - create
      - update
  - apiGroups:
      - druid.apache.org
    resources:
      - druids
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - druid.apache.org
    resources:
      - druids/status
    verbs:
      - get
      - update
      - patch
{{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "druid-operator.fullname" $ }}
  labels:
    {{- include "druid-operator.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - watch
      - create
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - create
      - update
  - apiGroups:
      - druid.apache.org
    resources:
      - druids
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - druid.apache.org
    resources:
      - druids/status
    verbs:
      - get
      - update
      - patch
{{- end }}
{{- end }}

---
# need clusterrole anyways
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "druid-operator.fullname" $ }}-sc
  labels:
    {{- include "druid-operator.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch