# Import the values when being called as dependency needs this line because of the dash '-'
# Not looping when WATCH_NAMESPACE is 'default' or ALL
{{- if and (.Values.env.WATCH_NAMESPACE) (ne .Values.env.WATCH_NAMESPACE "default") }}

# Split WATCH_NAMESPACE by commas and loop on them
{{- $watchedNamespaces := (split "," .Values.env.WATCH_NAMESPACE) -}}
{{- range $watchedNamespaces }}

# Look for desired namespace to create when not existent
{{- $relnamespace := (lookup "v1" "Namespace" "" .) -}}
{{- if empty $relnamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{- . }}"
{{- end }}

{{- end }}

{{- end }}
